services:
  database:
    image: mysql
    container_name: dc-ghl-mysql
    env_file:
      - ./docker.env
    expose:
      - 3306
    volumes:
      - dc-ghl-mysql-vol:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "database" ]
      interval: 2s
      timeout: 30s
      retries: 30

  redis:
    image: redis
    container_name: dc-ghl-redis
    expose:
      - 6379
    volumes:
      - dc-ghl-redis-vol:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 2s
      timeout: 30s
      retries: 30
    ports:
      - 6379

  backend:
    build: .
    container_name: dc-ghl-be
    ports:
      - 8080:8080
      - 9229:9229
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ${PWD}:/app
      # - D:\work-projects\ghl-be:/app
    env_file:
      - ./docker.env
    entrypoint: /app/docker-entrypoint.sh

volumes:
  dc-ghl-mysql-vol:
  dc-ghl-redis-vol:
